# Generated by Django 6.0.4 on 2026-05-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_semester_remove_document_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notify_users',
            field=models.BooleanField(default=True, help_text='Tick this box to send an email to all students about this new document.', verbose_name='Send Notification'),
        ),
    ]
